---
version: "3"
services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
        - POSTGRES_PASSWORD=segredo
        - POSTGRES_USER=rinha
    networks:
      - app_network
    volumes:
      - "./confs/postgresql.conf:/etc/postgresql/postgresql.conf"
      - "./confs/pg_init.sh:/docker-entrypoint-initdb.d/pg_init.sh"
      -  "./data:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rinha"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: "512MB"
  nginx:
    image: nginx
    networks:
      - app_network
    depends_on:
      - app
    volumes:
      - "./confs/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "8000:80"
    deploy:
      resources:
        limits:
          memory: "2GB"
  app:
    build:
      context: .
    networks:
      - app_network
    depends_on:
      postgres:
        condition: service_healthy
    deploy:
      replicas: 2
      resources:
        limits:
          memory: "256MB"
networks:
  app_network:
